#!/bin/bash

# Check ~/.vagrant.d exists

if [ ! -d ${HOME}/.vagrant.d ] ; then
	if ! vagrant version > /dev/null 2>&1 ; then
		echo "Directory ~/.vagrant.d is missing. Please create it by installing vagrant and typing: vagrant version"
		exit 1
	fi
fi

docker run -it --rm \
	-e LIBVIRT_DEFAULT_URI \
	-v /var/run/libvirt/:/var/run/libvirt/ \
	-v ~/.vagrant.d:/.vagrant.d \
	-v $(pwd):$(pwd)   \
	-w $(pwd)   \
	quay.io/lpabon/kubeup $@
