- hosts: all
  become: yes
  become_method: sudo
  vars_files:
    - "global_vars.yml"
  roles:
    - common

- hosts: ~.*master
  become: yes
  become_method: sudo
  vars_files:
    - "global_vars.yml"
  roles:
    - master
  environment:
    KUBECONFIG: '/etc/kubernetes/admin.conf'

- hosts: ~.*node.
  become: yes
  become_method: sudo
  vars_files:
    - "global_vars.yml"
  roles:
    - nodes
  environment:
    KUBECONFIG: '/etc/kubernetes/admin.conf'

- hosts: ~.*master
  become: yes
  become_method: sudo
  vars_files:
    - "global_vars.yml"
  roles:
    - final
  environment:
    KUBECONFIG: '/etc/kubernetes/admin.conf'
