- name: install v1.24 kubernetes
  yum: name={{ packages }} state=present disable_gpg_check=yes
  vars:
    packages:
      - kubelet-1.24.7-0
      - kubeadm-1.24.7-0
      - kubectl-1.24.7-0

- name: setting vars
  set_fact:
    kubeadm_kubernetes_version: stable-1.24
