# -*- mode: ruby -*-
# vi: set ft=ruby :
#
Vagrant.configure("2") do |config|
  config.vm.box = "fedora/25-cloud-base"
  config.vm.provider :libvirt do |lv|
     lv.memory = "10000"
     lv.cpus = 2
     lv.nested = true
  end
  config.vm.provision "shell", inline: <<-SHELL
     sudo dnf -y install git
     git clone https://github.com/lpabon/kubeup.git
  SHELL
end
